// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "optionbutton1.h"

/////////////////////////////////////////////////////////////////////////////
// COptionbutton1

IMPLEMENT_DYNCREATE(COptionbutton1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// COptionbutton1 properties

/////////////////////////////////////////////////////////////////////////////
// COptionbutton1 operations
